---
layout: post
---

= RichFaces Build Re-Structure
Lukas Fryc
2013-04-08
:awestruct-tags: [richfaces]

As we have announced we underwent huge refactoring of the RichFaces project structure as part of the RichFaces 5 efforts.

== Why?

We have simply identified over time that there are needs which the project doesn't reflect because it is not ready to support them.

We have reflected most of these needs as user stories. Let me just re-iterate ones which are related to final framework user:

=== User Perspective
____
As a *RichFaces user* I want to

* include only a *single jar* in my applications pom file so that I can easily make use of the RichFaces components and framework without requiring complicated changes to the build

* include only a *single namespace* for use of RichFaces components so that I can more quickly and easily author new pages, with all components being discoverable with IDE autocompletion

* use RichFaces *samples/examples as a starting point* for my project so that I can easily include the provided sample code in my application.
____

As you can read further in Where we are, we have succeeded to cover first two points completely!

=== Contributor Perspective

As a open source project we pretty much rely on simplicity of a build and code structure. If it is too hard for us to navigate in the project, how it can be hard for anyone else?

I won't dive into particular user stories, but let's say that *build is way, way simpler then it was*.

We believe that this re-structure will largely help us to develop great features planned for RichFaces 5 as quick as possible while maintaining even better stability.

And it should also encourage you to dive into the code!

== Where we are?

The Alpha1 is being released these days and as we designed, it is functionally identical with last release of RichFaces 4 available today (4.3.2).

We had make sure that everything works almost same - we even put extensive efforts to QA this release so (thanks guys!).

=== Dependencies

The only changes which were introduced is system of dependencies:

* Maven users should include just one dependency (`org.richfaces:richfaces`),
* Ant users should include just one JAR (`richfaces.jar`).

=== Namespaces

Additionally, the two RichFaces tag libraries (a4j/rich) were merged to one, so there is only one namespace (http://richfaces.org/rich) with renewed default prefix (`r`):

----
<!DOCTYPE html>
<html lang="en"
    xmlns="http://www.w3.org/1999/xhtml"
    ...
    xmlns:r="http://richfaces.org/rich">

</html>
----

Nothing you couldn't change in your project by sedding over whole code base. ;-)

----
sed -ri 's#xmlns:a4j="http://richfaces.org/a4j"##g'
sed -ri 's#xmlns:rich="http://richfaces.org/rich"#xmlns:r="http://richfaces.org/rich#g'
sed -ri 's#<(/?)(a4j|rich):#<\1r:#g'
----

Remember to commit all your progress before performing those steps: I can guarantee no warranties! :-)

=== Refactored Java Packages

The last concern is that we made sure the whole project is structured properly on a level of Java packages.

Your code will be affected mainly when you use lot of component bindings (`binding=#{...}`) or programatic component instantiation (`Application#createComponent(...)`) or when you define `PushServlet` / `ResourceServlet` in a `web.xml` configuration.

Note that changes of packages are done in a 1:1 fashion, so once you switch from RichFaces 4 to RichFaces 5, you just need to review & fix compilation failures and you are all set (statically typed languages FTW!).

=== Restructured Resources

As we merged all the components to single module, we found out that resources are structured pretty unwiedly. We did a cleanup so resource keys might be changed - you can go to the https://github.com/richfaces/richfaces/tree/master/framework/src/main/resources/META-INF/resources:[`META-INF/resources`] to see where the new resources lies.

=== Sample/Example Simplification?
==== Still Work in Progress

We didn't touch samples and a Showcase application a much - it's for specific reason - we want you to see Alpha1 as a first milestone for a migration to RichFaces 5 as this major release should not be migration nightmare.

<div class="alert alert-note">In fact, I imagine the migration path through the use of RichFaces 5 Alpha1 as a base where just small changes are needed, followed by upgrade to Beta/CR/Final releases which will already have all the new shiny goodness inside.</div>

The examples will be used to show and document usage of components as you can already see in a prototype of https://github.com/richfaces/richfaces/tree/master/framework/src/main/resources/META-INF/resources[Bootstrap Showcase] which was incredible effort of our precious community (yeah, I'm pointing your way, http://pauldijou.fr/[Paul Dijou]).

=== Give it a try!

That's it. For medium sized projects, this could be almost effortless migration (not that I'm encouraging your production system to alpha release :-) ).

However if you start a RichFaces project today on a green field, you can use `Alpha1` as a base for your development. As we will proceed further with upcoming milestones, you will be able to upgrade in order to evaluate shiny new components!